---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstackupload
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/mnt/bookstack/upload" #host location
